spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/broker
    username: broker
    password: broker
  rabbitmq:
    host: rabbitmq
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: broker
